# Generated by Django 3.0.3 on 2020-02-26 09:04

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.IntegerField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('coordinates', django.contrib.gis.db.models.fields.PointField(blank=True, srid=4326)),
                ('players', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('exits', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=1), size=4)),
                ('cooldown', models.IntegerField(blank=True)),
                ('errors', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=100), size=None)),
                ('messages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=None)),
            ],
        ),
    ]
