# Generated by Django 3.0.3 on 2020-02-27 02:12

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200227_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='cooldown',
        ),
        migrations.RemoveField(
            model_name='room',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='room',
            name='exits',
        ),
        migrations.RemoveField(
            model_name='room',
            name='items',
        ),
        migrations.RemoveField(
            model_name='room',
            name='messages',
        ),
        migrations.AlterField(
            model_name='room',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50), size=None),
        ),
    ]
