# Generated by Django 3.0.3 on 2020-02-27 02:16

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200227_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='players',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
    ]
