# Generated by Django 3.0.3 on 2020-02-27 02:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200227_0216'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='cooldown',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='errors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(blank=True, max_length=100), null=True, size=None),
        ),
        migrations.AddField(
            model_name='room',
            name='exits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1), null=True, size=4),
        ),
        migrations.AddField(
            model_name='room',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), null=True, size=None),
        ),
        migrations.AddField(
            model_name='room',
            name='messages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), null=True, size=None),
        ),
    ]
